light:
    - !include display/windows_display_light.yaml
    - !include display/linux_display.yaml
    - !include display/mac_display.yaml

sensor:
    # 播放状态
    - name: media_windows_status
      unique_id: sucicada/home/media/windows/status  # 这里必须有才生效
      state_topic: "sucicada/home/media/windows/status"  # 替换成你实际的 topic
    
    # - name: media_windows_is_muted
    #   unique_id: sucicada/home/media/windows/is_muted
    #   state_topic: "sucicada/home/media/windows/is_muted"
      
    # - name: media_windows_volume
    #   unique_id: sucicada/home/media/windows/volume
    #   state_topic: "sucicada/home/media/windows/volume"
    - name: media_linux_status
      unique_id: sucicada/home/media/linux/status  # 这里必须有才生效
      state_topic: "sucicada/home/media/linux/status"  # 替换成你实际的 topic
    
